name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate
      
    - name: Install PHP dependencies
      run: sudo apt install php7.4-cli php7.4-zip php7.4-readline php7.4-xmlreader php7.4-xsl php7.4-mysqli php7.4-json php7.4-pdo php7.4-curl php7.4-ftp php7.4-mbstring

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Build CLI script
      run: sudo php invision\ dev\ helper app:build -vvv
