name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: php7.2 /usr/bin/composer validate

    - name: Install dependencies
      run: php7.2 /usr/bin/composer install --prefer-dist --no-progress --no-suggest

    - name: Build CLI script
      run: sudo php7.2 -v; sudo php7.2 invision\ dev\ helper app:build -vvv
